Rails:
  Enabled: true


AllCops:
  TargetRubyVersion: 2.5.1

  Exclude:
    - 'app/views/**/*'
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'scripts/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'config/initializers/devise.rb'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'spec/controller_helpers.rb'
    - 'Gemfile*'
    - ''

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/StringLiterals:
  Exclude:
    - 'config/**/*'

# Increase block length for tests
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'


Style/ClassAndModuleChildren:
  Enabled: false
