language: ruby
rvm:
  - 2.5.1
env:
  - DATABASE_USERNAME=travis
before_install:
  - gem install bundler
before_script:
  - bundle exec rake db:create db:migrate
notifications:
  - false
script:
  - bundle exec rspec
  - bundle exec rubocop

