default: &default
  adapter:  postgresql
  encoding: utf8
  host:     <%= ENV.fetch('DATABASE_HOST', '127.0.0.1') %>
  port:     <%= ENV.fetch('DATABASE_PORT', 5432) %>
  pool:     <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  username: <%= ENV.fetch('DATABASE_USERNAME') %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: <%= "#{ENV.fetch('DATABASE_NAME') { ENV.fetch('APP_NAME', 'application') }.dup.concat('_development')}" %>

test:
  <<: *default
  database: <%= "#{ENV.fetch('DATABASE_NAME') { ENV.fetch('APP_NAME', 'application') }.dup.concat('_test')}#{ENV['TEST_ENV_NUMBER']}" %>

staging:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME') { ENV.fetch('APP_NAME', 'application').dup.concat('_staging') } %>

production:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME') { ENV.fetch('APP_NAME', 'application').dup.concat('_production') } %>
